### ISSUE TITLE
Create CalendarAllEvents/Dashboard Lower

### ISSUE THREAD

**Issue by TBolton2000** [TBolton2000/concord#18]
Create a Table Title(just text above the table) and a Material UI Table with headers and all data displayed
Write code in `DashboardAllEvents.tsx`. 

The lower part of this dashboard.
![image](https://user-images.githubusercontent.com/52944725/95365525-e3364280-0897-11eb-844e-0a0624167f1e.png)

Try adding more elements to "data" to display

Try adding clickable headers that change the sort by method for this table (look this up it has been done so many times before, there are probably really good tutorials for this!)

Try adding the '+' button as a material-ui icon button to the top left of the table. It does not have to do anything at the moment

**Comment by macbookfilip** [comment]
Hello, I would like to try to working on this issue. Could you assign it to me please? Thank you

**Comment by TBolton2000** [comment]
> Hello, I would like to try to working on this issue. Could you assign it to me please? Thank you

hi @macbookfilip this is a class project for the collaborators in this group. We are going to do all the work ourselves, sorry!
